#Name: Zoe Debyl
#Date: 2/7/2023
#Assignment: Assignment2

all: q1 q2

q1: A3_Q1.c
	gcc -Wall -std=c99 A3_Q1.c -o q1

q2: A3_Q2.c
	gcc -Wall -std=c99 A3_Q2.c -o q2

clean:
	rm *.o q1 q2
