#Name: Zoe Debyl
#Date: 3/27/2023
#Assignment: Assignment 4

all: q1 q2

q1: A5_Q1.c
	gcc -Wall -std=c99 A5_Q1.c -o q1 -lm

q2: A5_Q2.c
	gcc -Wall -std=c99 A5_Q2.c -o q2

clean:
	rm q1 q2
